site_name: ISC-Blog
#site_url: http://123.249.41.193
site_author: ISC-WEB
site_description: 浪潮俱乐部的博客站

theme:
  name: material
  logo: images/inspur.png
  favicon: images/inspur_logo.png
  features:
    - search.suggest
    - search.highlight
    - header.autohide
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.code.copy
  icon:
    repo: fontawesome/brands/git-alt
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换暗色模式
      primary: blue grey #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: light blue # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: light blue # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]
      toggle:
        icon: material/brightness-4
        name: 切换亮色模式

repo_name: 本站GitHub仓库
repo_url: https://github.com/711lxsky/ISCBlogTest.git

copyright: Copyright &copy XDU-ISC-WEB

extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/solid/house-chimney
      name: 西电浪潮俱乐部官网
      link: http://123.249.41.193/index.html
    - icon: fontawesome/brands/github
      name: XDU-ISC
      link: https://github.com/ISC-XDU
      
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
